import { db } from '../src/lib/db';

const SERVICES = [
  {
    name: 'Servis Laptop & MacBook',
    slug: 'servis-laptop-macbook',
    category: 'Elektronik',
    shortDesc: 'Perbaikan segala jenis kerusakan laptop dan MacBook',
    detailDesc: 'Servis lengkap laptop & MacBook: motherboard, power IC, layar, keyboard, baterai. Garansi 30 hari. Panggilan gratis area Cirebon kota.',
    price: 150000,
    priceMax: 1500000,
    benefit1: 'Gratis Cek Kerusakan',
    benefit2: 'Garansi 30 Hari',
    benefit3: 'Sparepart Original',
    benefit4: 'Teknisi Berpengalaman',
    benefit5: 'Panggilan Gratis Cirebon',
    waText: 'Halo Mas Iis, saya mau servis laptop/macbook',
    imageUrl: '/services/laptop.svg',
    bonus: 'Free thermal paste',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 1,
  },
  {
    name: 'Bimbingan Skripsi/Tesis/Disertasi/Artikel Ilmiah',
    slug: 'bimbingan-skripsi-tesis-disertasi-artikel-ilmiah',
    category: 'Pendidikan',
    shortDesc: 'Bimbingan dari judul sampai sidang, dijamin ACC',
    detailDesc: 'Bimbingan skripsi, tesis, disertasi, dan artikel ilmiah semua jurusan. Online via Zoom/Meet. Coding, jurnal, SPSS, AMOS. Dijamin ACC atau bimbingan ulang gratis.',
    price: 1500000,
    priceMax: 5000000,
    benefit1: 'Jaminan Sampai Lulus',
    benefit2: 'Online & Offline',
    benefit3: 'Semua Jurusan',
    benefit4: 'Revisi Gratis',
    benefit5: 'Mentor Berpengalaman',
    waText: 'Halo Mas Iis, saya mau bimbingan skripsi/tesis/disertasi',
    imageUrl: '/services/skripsi.svg',
    bonus: 'Free cek Turnitin & AI',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 2,
  },
  {
    name: 'Jasa Cek Turnitin & AI',
    slug: 'jasa-cek-turnitin-ai',
    category: 'Pendidikan',
    shortDesc: 'Cek plagiarisme Turnitin & deteksi AI dengan laporan PDF resmi',
    detailDesc: 'Cek similarity Turnitin resmi dan deteksi konten AI. Laporan PDF lengkap. Hasil akurat sama kampus. Proses 1-24 jam.',
    price: 50000,
    priceMax: 150000,
    benefit1: 'Laporan PDF Resmi',
    benefit2: 'Akurat Sama Kampus',
    benefit3: 'Proses Cepat 1-24 Jam',
    benefit4: 'Deteksi AI + Plagiarisme',
    benefit5: 'Privasi Terjaga',
    waText: 'Halo Mas Iis, saya mau cek Turnitin & AI',
    imageUrl: '/services/turnitin.svg',
    bonus: 'Free paraphrase 2 halaman',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 3,
  },
  {
    name: 'Paket Belajar A, B, C',
    slug: 'paket-belajar-abc',
    category: 'Pendidikan',
    shortDesc: 'Bimbingan belajar terstruktur dengan try out rutin',
    detailDesc: 'Paket belajar lengkap untuk SD, SMP, SMA. Try out rutin, evaluasi berkala, tes minat bakat. Privat atau grup.',
    price: 300000,
    priceMax: 800000,
    benefit1: 'Try Out Rutin',
    benefit2: 'Evaluasi Berkala',
    benefit3: 'Privat atau Grup',
    benefit4: 'Materi Terstruktur',
    benefit5: 'Progress Report',
    waText: 'Halo Mas Iis, saya mau daftar paket belajar',
    imageUrl: '/services/belajar.svg',
    bonus: 'Free tes minat bakat',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 4,
  },
  {
    name: 'Jasa Jahit Baju Borongan Sekolah',
    slug: 'jasa-jahit-borongan-sekolah',
    category: 'Fashion',
    shortDesc: 'Jahit seragam sekolah borongan, kualitas rapi & kuat',
    detailDesc: 'Jasa jahit baju seragam sekolah borongan. Jahitan rapi & kuat. Bisa custom logo dan sablon. Minimum order 20 pcs.',
    price: 45000,
    priceMax: 150000,
    benefit1: 'Jahitan Rapi & Kuat',
    benefit2: 'Bisa Custom Logo',
    benefit3: 'Minimum 20 Pcs',
    benefit4: 'Tepat Waktu',
    benefit5: 'Harga Borongan',
    waText: 'Halo Mas Iis, saya mau jahit baju borongan',
    imageUrl: '/services/jahit.svg',
    bonus: 'Gratis Sample 1 Pcs',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 5,
  },
  {
    name: 'Desain Grafis Profesional',
    slug: 'desain-grafis-profesional',
    category: 'Digital',
    shortDesc: 'Logo, banner, feed IG, undangan, kartu nama',
    detailDesc: 'Jasa desain grafis profesional: logo, banner, feed Instagram, undangan digital, kartu nama, brosur. Revisi unlimited sampai puas.',
    price: 250000,
    priceMax: 1500000,
    benefit1: 'Revisi Unlimited',
    benefit2: 'File Semua Format',
    benefit3: 'Desainer Berpengalaman',
    benefit4: 'Proses 1-3 Hari',
    benefit5: 'Portfolio Lengkap',
    waText: 'Halo Mas Iis, saya mau jasa desain grafis',
    imageUrl: '/services/desain.svg',
    bonus: 'Bonus kartu nama',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 6,
  },
  {
    name: 'Jasa Agency Acara Lengkap',
    slug: 'jasa-agency-acara',
    category: 'Event',
    shortDesc: 'Paket all-in satu tahun untuk event organizer',
    detailDesc: 'Jasa agency acara lengkap: MC, dekorasi, sound system, dokumentasi. Paket all-in untuk 1 tahun. Termasuk free MC profesional.',
    price: 5000000,
    priceMax: 25000000,
    benefit1: 'Paket All-In 1 Tahun',
    benefit2: 'MC Profesional',
    benefit3: 'Dokumentasi Lengkap',
    benefit4: 'Dekorasi Premium',
    benefit5: 'Sound System Lengkap',
    waText: 'Halo Mas Iis, saya mau jasa agency acara',
    imageUrl: '/services/agency.svg',
    bonus: 'Free MC',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 7,
  },
  {
    name: 'Jasa MC Profesional',
    slug: 'jasa-mc-profesional',
    category: 'Event',
    shortDesc: 'MC bilingual Indonesia-Sunda untuk segala acara',
    detailDesc: 'Jasa MC profesional bilingual Indonesia-Sunda. Wedding, khitanan, seminar, lomba. Susun rundown dan sistem lengkap.',
    price: 750000,
    priceMax: 3000000,
    benefit1: 'Bilingual Indonesia-Sunda',
    benefit2: 'Susun Sistem Lengkap',
    benefit3: 'Gratis Susun Rundown',
    benefit4: 'Berpengalaman 10+ Tahun',
    benefit5: 'Energi & Humor',
    waText: 'Halo Mas Iis, saya mau jasa MC',
    imageUrl: '/services/mc.svg',
    bonus: 'Gratis Susun Rundown',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 8,
  },
  {
    name: 'Gambus & El-Husna (Sound System)',
    slug: 'gambus-elhusna-sound-system',
    category: 'Event',
    shortDesc: 'Sewa sound system lengkap untuk acara gambusan & el-husna',
    detailDesc: 'Paket gambus dan el-husna lengkap: sound system, mic, speaker. Lagu bisa request. Tersedia paket 1-3 hari.',
    price: 1500000,
    priceMax: 5000000,
    benefit1: 'Sound System Lengkap',
    benefit2: 'Lagu Bisa Request',
    benefit3: 'Free 2 Lagu Tambahan',
    benefit4: 'Operator Berpengalaman',
    benefit5: 'Paket 1-3 Hari',
    waText: 'Halo Mas Iis, saya mau sewa gambus/el-husna',
    imageUrl: '/services/gambir.svg',
    bonus: 'Free 2 lagu tambahan',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 9,
  },
  {
    name: 'Jual Beli Kambing Qurban & Aqiqah',
    slug: 'jual-beli-kambing-qurban',
    category: 'Peternakan',
    shortDesc: 'Kambing qurban & aqiqah sesuai syariat Islam',
    detailDesc: 'Jual beli kambing qurban dan aqiqah. Sesuai syariat Islam. Sehat, gemuk, jadi 3 hari. Gratis sembelih dan packing.',
    price: 2500000,
    priceMax: 5000000,
    benefit1: 'Sesuai Syariat Islam',
    benefit2: 'Jadi 3 Hari',
    benefit3: 'Gratis Sembelih',
    benefit4: 'Kambing Sehat & Gemuk',
    benefit5: 'Bisa Antar',
    waText: 'Halo Mas Iis, saya mau kambing qurban/aqiqah',
    imageUrl: '/services/kambing.svg',
    bonus: 'Gratis Sembelih',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 10,
  },
  {
    name: 'Website Profil Minimalis',
    slug: 'website-profil-minimalis',
    category: 'IT',
    shortDesc: 'Website company profile, toko online, landing page',
    detailDesc: 'Jasa pembuatan website: company profile, toko online, landing page. Desain minimalis modern. Gratis domain & hosting 1 tahun.',
    price: 1500000,
    priceMax: 10000000,
    benefit1: 'Desain Minimalis Modern',
    benefit2: 'Gratis Domain 1 Tahun',
    benefit3: 'Gratis Maintenance 1 Bulan',
    benefit4: 'SEO Friendly',
    benefit5: 'Responsive Mobile',
    waText: 'Halo Mas Iis, saya mau buat website',
    imageUrl: '/services/website.svg',
    bonus: 'Gratis Maintenance 1 Bulan',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 11,
  },
  {
    name: 'Konsultan Manajemen Sekolah',
    slug: 'konsultan-manajemen-sekolah',
    category: 'Konsultan',
    shortDesc: 'Bimbingan akreditasi A dan SOP lengkap sekolah',
    detailDesc: 'Konsultan manajemen sekolah: bimbingan akreditasi A, SOP lengkap, sistem administrasi. Jaminan lolos akreditasi.',
    price: 3000000,
    priceMax: 15000000,
    benefit1: 'Bimbingan Akreditasi A',
    benefit2: 'Jaminan Lolos',
    benefit3: 'Bonus SOP Lengkap',
    benefit4: 'Sistem Administrasi',
    benefit5: 'Pendampingan 1 Tahun',
    waText: 'Halo Mas Iis, saya mau konsultasi manajemen sekolah',
    imageUrl: '/services/konsultan.svg',
    bonus: 'Bonus SOP lengkap',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 12,
  },
  {
    name: 'CEO Copywriting',
    slug: 'ceo-copywriting',
    category: 'Digital',
    shortDesc: 'Copywriting formula AIDA & PAS untuk bisnis',
    detailDesc: 'Jasa copywriting profesional: formula AIDA & PAS, riset produk mendalam, headline killer. Cocok untuk landing page dan iklan.',
    price: 500000,
    priceMax: 3000000,
    benefit1: 'Formula AIDA & PAS',
    benefit2: 'Riset Produk Mendalam',
    benefit3: 'Bonus 10 Headline',
    benefit4: 'Conversion-Focused',
    benefit5: 'Revisi Sampai Pas',
    waText: 'Halo Mas Iis, saya mau jasa copywriting',
    imageUrl: '/services/copywriting.svg',
    bonus: 'Bonus 10 Headline',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 13,
  },
  {
    name: 'Jasa Kaligrafi Arab',
    slug: 'jasa-kaligrafi-arab',
    category: 'Seni',
    shortDesc: 'Kaligrafi Arab di kanvas, kayu, atau kaca',
    detailDesc: 'Jasa kaligrafi Arab: khat, naskhi, tsuluts, diwani. Media kanvas, kayu, kaca. Free bingkai untuk ukuran tertentu.',
    price: 300000,
    priceMax: 2000000,
    benefit1: 'Khat Berbagai Gaya',
    benefit2: 'Media Kanvas/Kayu/Kaca',
    benefit3: 'Free Bingkai',
    benefit4: 'Custom Ukuran',
    benefit5: 'Pengerjaan 3-7 Hari',
    waText: 'Halo Mas Iis, saya mau jasa kaligrafi',
    imageUrl: '/services/kaligrafi.svg',
    bonus: 'Free bingkai',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 14,
  },
  {
    name: 'Hiasan Pigura Custom',
    slug: 'hiasan-pigura-custom',
    category: 'Seni',
    shortDesc: 'Pigura dan hiasan dinding desain custom eksklusif',
    detailDesc: 'Jasa pembuatan pigura dan hiasan dinding custom eksklusif. Desain sesuai permintaan. Pengerjaan 7 hari. Bonus box packaging.',
    price: 250000,
    priceMax: 1500000,
    benefit1: 'Desain Custom Eksklusif',
    benefit2: 'Pengerjaan 7 Hari',
    benefit3: 'Bonus Box',
    benefit4: 'Bahan Premium',
    benefit5: 'Bisa Combo Set',
    waText: 'Halo Mas Iis, saya mau pesan pigura/hiasan',
    imageUrl: '/services/pigura.svg',
    bonus: 'Bonus Box',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 15,
  },
  {
    name: 'Hias Taman Profesional',
    slug: 'hias-taman-profesional',
    category: 'Seni',
    shortDesc: 'Jasa hias taman berpengalaman 40 tahun',
    detailDesc: 'Jasa hias taman profesional dengan pengalaman 40 tahun. Desain taman minimalis, taman Jepang, taman tropis. Garansi tanaman 1 bulan.',
    price: 500000,
    priceMax: 10000000,
    benefit1: 'Pengalaman 40 Tahun',
    benefit2: 'Desain Custom',
    benefit3: 'Garansi Tanaman 1 Bulan',
    benefit4: 'Bahan Premium',
    benefit5: 'Maintenance Bulanan',
    waText: 'Halo Mas Iis, saya mau jasa hias taman',
    imageUrl: '/services/taman.svg',
    bonus: 'Gratis konsultasi desain',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 16,
  },
  {
    name: 'Jasa Hiburan Angklung',
    slug: 'jasa-hiburan-angklung',
    category: 'Event',
    shortDesc: '10 personil angklung dengan kostum tradisional',
    detailDesc: 'Jasa hiburan angklung: 10 personil, kostum tradisional, free interaktif 15 menit. Cocok untuk acara adat, pernikahan, khitanan.',
    price: 1200000,
    priceMax: 3000000,
    benefit1: '10 Personil Angklung',
    benefit2: 'Kostum Tradisional',
    benefit3: 'Free Interaktif 15 Menit',
    benefit4: 'Lagu Sunda & Nasional',
    benefit5: 'Bisa Request Lagu',
    waText: 'Halo Mas Iis, saya mau jasa angklung',
    imageUrl: '/services/angklung.svg',
    bonus: 'Free interaktif 15 menit',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 17,
  },
];

async function main() {
  console.log('🌱 Seeding database...');

  // Clear existing data
  await db.landingPage.deleteMany();
  await db.article.deleteMany();
  await db.chatLog.deleteMany();
  await db.service.deleteMany();

  // Seed services
  for (const svc of SERVICES) {
    const service = await db.service.create({ data: svc });
    // Auto-create landing page for each service
    await db.landingPage.create({
      data: {
        serviceId: service.id,
        headline: svc.name,
        subheadline: svc.shortDesc,
        ctaText: 'Hubungi Sekarang',
        sections: JSON.stringify([
          { type: 'hero', title: svc.name, subtitle: svc.shortDesc },
          { type: 'benefits', title: 'Keunggulan Layanan', items: [svc.benefit1, svc.benefit2, svc.benefit3, svc.benefit4, svc.benefit5] },
          { type: 'pricing', title: 'Harga', price: svc.price, priceMax: svc.priceMax },
          { type: 'cta', title: 'Pesan Sekarang', bonus: svc.bonus },
        ]),
      },
    });
  }

  // Seed sample articles
  await db.article.createMany({
    data: [
      {
        title: 'Tips Merawat Laptop Agar Awet',
        slug: 'tips-merawat-laptop',
        excerpt: 'Pelajari cara merawat laptop agar tetap performa optimal selama bertahun-tahun.',
        content: '<h2>1. Bersihkan Secara Rutin</h2><p>Bersihkan keyboard dan layar minimal 1 minggu sekali...</p><h2>2. Jangan Makan di Dekat Laptop</h2><p>Remah makanan bisa masuk ke keyboard...</p><h2>3. Gunakan Cooling Pad</h2><p>Overheating adalah musuh utama laptop...</p>',
        published: true,
      },
      {
        title: 'Cara Menyelesaikan Skripsi 1 Bulan',
        slug: 'skripsi-1-bulan',
        excerpt: 'Strategi praktis menyelesaikan skripsi dalam waktu singkat tanpa stres.',
        content: '<h2>1. Tentukan Judul Secepat Mungkin</h2><p>Jangan terlalu lama mencari judul sempurna...</p><h2>2. Buat Timeline Ketat</h2><p>Bagi waktu per bab...</p>',
        published: true,
      },
      {
        title: 'Mengapa Website Penting untuk Bisnis',
        slug: 'website-untuk-bisnis',
        excerpt: 'Alasan mengapa setiap bisnis membutuhkan website di era digital.',
        content: '<h2>1. Kredibilitas Bisnis</h2><p>75% konsumen menilai kredibilitas dari website...</p>',
        published: true,
      },
    ],
  });

  const count = await db.service.count();
  console.log(`✅ Seeded ${count} services with landing pages and articles!`);
}

main()
  .catch(console.error)
  .finally(() => db.$disconnect());
