import { db } from '@/lib/db'
import { NextRequest, NextResponse } from 'next/server'

// Setup endpoint: seeds the database with all services and data
// Call: GET /api/setup
// If force=true query param, it will delete existing data first and re-seed

const SERVICES = [
  {
    name: 'Servis Laptop & MacBook',
    slug: 'servis-laptop-macbook',
    category: 'Elektronik',
    shortDesc: 'Perbaikan segala jenis kerusakan laptop dan MacBook',
    detailDesc: 'Servis lengkap laptop dan MacBook: perbaikan motherboard, power IC, layar retak atau pecah, keyboard rusak, baterai drop, upgrade HDD ke SSD, upgrade RAM, install ulang Windows atau MacOS, hapus virus, perbaiki blue screen, solusi overheating. Garansi 30 hari sparepart, 14 hari software. Gratis panggilan area Cirebon kota.',
    price: 150000,
    priceMax: 1500000,
    benefit1: 'Gratis Cek Kerusakan',
    benefit2: 'Garansi 30 Hari',
    benefit3: 'Sparepart Original',
    benefit4: 'Teknisi Berpengalaman 8+ Tahun',
    benefit5: 'Panggilan Gratis Cirebon',
    waText: 'Halo Mas Iis, saya mau servis laptop atau MacBook',
    imageUrl: '/services/laptop.svg',
    bonus: 'Free thermal paste',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 1,
  },
  {
    name: 'Bimbingan Skripsi/Tesis/Disertasi/Artikel Ilmiah',
    slug: 'bimbingan-skripsi-tesis-disertasi-artikel-ilmiah',
    category: 'Pendidikan',
    shortDesc: 'Bimbingan dari judul sampai sidang, dijamin ACC',
    detailDesc: 'Bimbingan skripsi, tesis, disertasi, dan artikel ilmiah semua jurusan tanpa terkecuali. Online via Zoom atau Google Meet, juga bisa offline. Coding, jurnal internasional, SPSS, AMOS, LISREL, NVivo, Stata, dan R. Dijamin ACC atau bimbingan ulang gratis tanpa batas waktu.',
    price: 1500000,
    priceMax: 5000000,
    benefit1: 'Jaminan Sampai Lulus',
    benefit2: 'Online dan Offline',
    benefit3: 'Semua Jurusan',
    benefit4: 'Revisi Gratis Tanpa Batas',
    benefit5: 'Mentor S2 dan S3 Berpengalaman',
    waText: 'Halo Mas Iis, saya mau bimbingan skripsi atau tesis atau disertasi',
    imageUrl: '/services/skripsi.svg',
    bonus: 'Free cek Turnitin dan AI',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 2,
  },
  {
    name: 'Jasa Cek Turnitin & AI',
    slug: 'jasa-cek-turnitin-ai',
    category: 'Pendidikan',
    shortDesc: 'Cek plagiarisme Turnitin dan deteksi AI dengan laporan PDF resmi',
    detailDesc: 'Cek similarity Turnitin resmi dan deteksi konten AI. Laporan PDF lengkap resmi sama persis dengan kampus. Proses 1 sampai 24 jam. Akurasi 99%. Tersedia paket paraphrase untuk menurunkan similarity.',
    price: 50000,
    priceMax: 150000,
    benefit1: 'Laporan PDF Resmi',
    benefit2: 'Akurat Sama Kampus',
    benefit3: 'Proses Cepat 1 sampai 24 Jam',
    benefit4: 'Deteksi AI dan Plagiarisme',
    benefit5: 'Privasi Terjaga 100 Persen',
    waText: 'Halo Mas Iis, saya mau cek Turnitin dan AI',
    imageUrl: '/services/turnitin.svg',
    bonus: 'Free paraphrase 2 halaman',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 3,
  },
  {
    name: 'LES dan Privat Pelajaran SD dan TK',
    slug: 'les-privat-pelajaran-sd-tk',
    category: 'Pendidikan',
    shortDesc: 'Bimbingan belajar privat untuk anak SD dan TK dengan pendekatan menyenangkan',
    detailDesc: 'LES dan privat pelajaran untuk anak SD kelas 1 sampai 6 dan TK. Pendekatan belajar menyenangkan. Materi sesuai kurikulum Merdeka. Evaluasi berkala setiap minggu. Laporan progress ke orang tua per bulan. Privat 1-on-1 atau grup kecil 3-5 anak.',
    price: 200000,
    priceMax: 600000,
    benefit1: 'Guru Sabar dan Menyenangkan',
    benefit2: 'Materi Sesuai Kurikulum Merdeka',
    benefit3: 'Privat atau Grup Kecil',
    benefit4: 'Laporan Progress ke Orang Tua',
    benefit5: 'Evaluasi Berkala Setiap Minggu',
    waText: 'Halo Mas Iis, saya mau daftar les privat SD atau TK',
    imageUrl: '/services/belajar.svg',
    bonus: 'Free tes minat bakat anak',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 4,
  },
  {
    name: 'Jasa Jahit Baju Borongan Sekolah',
    slug: 'jasa-jahit-borongan-sekolah',
    category: 'Fashion',
    shortDesc: 'Jahit seragam sekolah borongan, kualitas rapi dan kuat',
    detailDesc: 'Jasa jahit baju seragam sekolah borongan. Jahitan rapi dan kuat menggunakan mesin industrial. Bisa custom logo bordir dan sablon. Minimum order 20 pcs.',
    price: 45000,
    priceMax: 150000,
    benefit1: 'Jahitan Rapi dan Kuat',
    benefit2: 'Bisa Custom Logo Bordir dan Sablon',
    benefit3: 'Minimum 20 Pcs',
    benefit4: 'Tepat Waktu',
    benefit5: 'Harga Borongan Kompetitif',
    waText: 'Halo Mas Iis, saya mau jahit baju borongan sekolah',
    imageUrl: '/services/jahit.svg',
    bonus: 'Gratis Sample 1 Pcs',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 5,
  },
  {
    name: 'Desain Grafis Profesional',
    slug: 'desain-grafis-profesional',
    category: 'Digital',
    shortDesc: 'Logo, banner, feed IG, undangan, kartu nama, dan lainnya',
    detailDesc: 'Jasa desain grafis profesional: logo, banner, feed Instagram, undangan digital, kartu nama, brosur, packaging, menu restoran, sertifikat, dan ID card. Revisi unlimited sampai puas. File dikirim semua format AI PSD PDF PNG JPG.',
    price: 250000,
    priceMax: 1500000,
    benefit1: 'Revisi Unlimited Sampai Puas',
    benefit2: 'File Semua Format AI PSD PDF PNG JPG',
    benefit3: 'Desainer Berpengalaman 5+ Tahun',
    benefit4: 'Proses 1 sampai 3 Hari',
    benefit5: 'Portfolio Lengkap',
    waText: 'Halo Mas Iis, saya mau jasa desain grafis',
    imageUrl: '/services/desain.svg',
    bonus: 'Bonus kartu nama',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 6,
  },
  {
    name: 'Jasa Agency Acara Lengkap',
    slug: 'jasa-agency-acara',
    category: 'Event',
    shortDesc: 'Paket all-in satu tahun untuk event organizer',
    detailDesc: 'Jasa agency acara lengkap all-in-one. MC, dekorasi, sound system, dokumentasi foto dan video, lighting, dan rekomendasi catering. Paket untuk 1 tahun atau per event. Free MC profesional di semua paket.',
    price: 5000000,
    priceMax: 25000000,
    benefit1: 'Paket All-In 1 Tahun',
    benefit2: 'MC Profesional Free',
    benefit3: 'Dokumentasi Lengkap Foto dan Video',
    benefit4: 'Dekorasi Premium',
    benefit5: 'Sound System Lengkap',
    waText: 'Halo Mas Iis, saya mau jasa agency acara',
    imageUrl: '/services/agency.svg',
    bonus: 'Free MC Profesional',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 7,
  },
  {
    name: 'Jasa MC Profesional',
    slug: 'jasa-mc-profesional',
    category: 'Event',
    shortDesc: 'MC bilingual Indonesia-Sunda untuk segala acara',
    detailDesc: 'MC profesional bilingual Indonesia-Sunda. Berpengalaman 10+ tahun. Wedding, khitanan, seminar, lomba, reuni, halalbihalal. Susun rundown dan sistem lengkap. Gratis susun rundown di semua paket.',
    price: 750000,
    priceMax: 3000000,
    benefit1: 'Bilingual Indonesia-Sunda',
    benefit2: 'Susun Sistem dan Rundown Lengkap',
    benefit3: 'Gratis Susun Rundown',
    benefit4: 'Berpengalaman 10+ Tahun',
    benefit5: 'Energi dan Humor Natural',
    waText: 'Halo Mas Iis, saya mau jasa MC',
    imageUrl: '/services/mc.svg',
    bonus: 'Gratis Susun Rundown',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 8,
  },
  {
    name: 'Gambus dan El-Husna Sound System',
    slug: 'gambus-elhusna-sound-system',
    category: 'Event',
    shortDesc: 'Sewa sound system lengkap untuk acara gambusan dan el-husna',
    detailDesc: 'Paket gambus dan el-husna lengkap: sound system, mic wireless, speaker 12-15 inch, mixer, dan player. Lagu bisa request. Tersedia paket 1-3 hari. Cocok untuk gambusan, Maulid Nabi, haul, tahlilan, dan acara keagamaan lainnya.',
    price: 1500000,
    priceMax: 5000000,
    benefit1: 'Sound System Lengkap',
    benefit2: 'Lagu Bisa Request',
    benefit3: 'Free 2 Lagu Tambahan',
    benefit4: 'Operator Berpengalaman',
    benefit5: 'Paket 1 sampai 3 Hari',
    waText: 'Halo Mas Iis, saya mau sewa gambus atau el-husna',
    imageUrl: '/services/gambir.svg',
    bonus: 'Free 2 lagu tambahan',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 9,
  },
  {
    name: 'Jual Beli Kambing Qurban dan Aqiqah',
    slug: 'jual-beli-kambing-qurban',
    category: 'Peternakan',
    shortDesc: 'Kambing qurban dan aqiqah sesuai syariat Islam',
    detailDesc: 'Jual beli kambing qurban dan aqiqah. Sesuai syariat Islam. Sehat, gemuk, umur cukup. Jadi 3 hari. Gratis sembelih dan packing. Bisa antar ke rumah area Cirebon.',
    price: 2500000,
    priceMax: 5000000,
    benefit1: 'Sesuai Syariat Islam',
    benefit2: 'Jadi 3 Hari',
    benefit3: 'Gratis Sembelih dan Packing',
    benefit4: 'Kambing Sehat dan Gemuk',
    benefit5: 'Bisa Antar Area Cirebon',
    waText: 'Halo Mas Iis, saya mau kambing qurban atau aqiqah',
    imageUrl: '/services/kambing.svg',
    bonus: 'Gratis Sembelih',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 10,
  },
  {
    name: 'Website Profil Minimalis',
    slug: 'website-profil-minimalis',
    category: 'IT',
    shortDesc: 'Website company profile, toko online, landing page',
    detailDesc: 'Jasa pembuatan website: company profile, toko online, landing page, blog, portfolio. Desain minimalis modern. Gratis domain dot com dan hosting 1 tahun. SEO friendly. Responsive mobile. Gratis maintenance 1 bulan.',
    price: 1500000,
    priceMax: 10000000,
    benefit1: 'Desain Minimalis Modern',
    benefit2: 'Gratis Domain dot com 1 Tahun',
    benefit3: 'Gratis Maintenance 1 Bulan',
    benefit4: 'SEO Friendly',
    benefit5: 'Responsive Mobile',
    waText: 'Halo Mas Iis, saya mau buat website',
    imageUrl: '/services/website.svg',
    bonus: 'Gratis Maintenance 1 Bulan',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 11,
  },
  {
    name: 'Konsultan Manajemen Sekolah',
    slug: 'konsultan-manajemen-sekolah',
    category: 'Konsultan',
    shortDesc: 'Bimbingan akreditasi A dan SOP lengkap sekolah',
    detailDesc: 'Konsultan manajemen sekolah profesional. Bimbingan akreditasi A, SOP lengkap, sistem administrasi digital, penyiapan dokumen visitasi, simulasi visitasi, pendampingan 1 tahun. Jaminan lolos akreditasi.',
    price: 3000000,
    priceMax: 15000000,
    benefit1: 'Bimbingan Akreditasi A',
    benefit2: 'Jaminan Lolos Akreditasi',
    benefit3: 'Bonus SOP Lengkap',
    benefit4: 'Sistem Administrasi Digital',
    benefit5: 'Pendampingan 1 Tahun',
    waText: 'Halo Mas Iis, saya mau konsultasi manajemen sekolah',
    imageUrl: '/services/konsultan.svg',
    bonus: 'Bonus SOP lengkap',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 12,
  },
  {
    name: 'CEO Copywriting',
    slug: 'ceo-copywriting',
    category: 'Digital',
    shortDesc: 'Copywriting formula AIDA dan PAS untuk bisnis',
    detailDesc: 'Jasa copywriting profesional menggunakan formula AIDA dan PAS. Riset produk dan target market mendalam. Cocok untuk landing page, iklan Facebook/Instagram/Google, email marketing, product description, dan social media caption. Revisi sampai pas tanpa limit.',
    price: 500000,
    priceMax: 3000000,
    benefit1: 'Formula AIDA dan PAS',
    benefit2: 'Riset Produk dan Market Mendalam',
    benefit3: 'Bonus 10 Headline Ampuh',
    benefit4: 'Conversion-Focused',
    benefit5: 'Revisi Sampai Pas Tanpa Limit',
    waText: 'Halo Mas Iis, saya mau jasa copywriting',
    imageUrl: '/services/copywriting.svg',
    bonus: 'Bonus 10 Headline',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 13,
  },
  {
    name: 'Jasa Kaligrafi Arab',
    slug: 'jasa-kaligrafi-arab',
    category: 'Seni',
    shortDesc: 'Kaligrafi Arab di kanvas, kayu, atau kaca',
    detailDesc: 'Jasa kaligrafi Arab dengan berbagai gaya khat: Naskhi, Tsuluts, Diwani, Farisi, Kufi, dan Riqaah. Media: kanvas, kayu, kaca, dinding. Custom ukuran. Free bingkai untuk ukuran di atas 50x70cm. Pengerjaan 3-7 hari kerja.',
    price: 300000,
    priceMax: 2000000,
    benefit1: 'Khat Berbagai Gaya Naskhi Tsuluts Diwani Farisi Kufi',
    benefit2: 'Media Kanvas Kayu Kaca Dinding',
    benefit3: 'Free Bingkai Ukuran di Atas 50x70',
    benefit4: 'Custom Ukuran Sesuai Permintaan',
    benefit5: 'Pengerjaan 3 sampai 7 Hari',
    waText: 'Halo Mas Iis, saya mau jasa kaligrafi',
    imageUrl: '/services/kaligrafi.svg',
    bonus: 'Free bingkai',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 14,
  },
  {
    name: 'Hiasan Pigura Custom',
    slug: 'hiasan-pigura-custom',
    category: 'Seni',
    shortDesc: 'Pigura dan hiasan dinding desain custom eksklusif',
    detailDesc: 'Jasa pembuatan pigura dan hiasan dinding custom eksklusif. Desain sesuai permintaan. Bahan premium: kayu jati, MDF, akrilik, logam. Pengerjaan 7 hari. Bonus box packaging untuk hadiah.',
    price: 250000,
    priceMax: 1500000,
    benefit1: 'Desain Custom Eksklusif',
    benefit2: 'Pengerjaan 7 Hari',
    benefit3: 'Bonus Box Packaging',
    benefit4: 'Bahan Premium Kayu Jati MDF Akrilik',
    benefit5: 'Bisa Combo Set',
    waText: 'Halo Mas Iis, saya mau pesan pigura atau hiasan',
    imageUrl: '/services/pigura.svg',
    bonus: 'Bonus Box',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 15,
  },
  {
    name: 'Hias Taman Profesional',
    slug: 'hias-taman-profesional',
    category: 'Seni',
    shortDesc: 'Jasa hias taman berpengalaman 40 tahun',
    detailDesc: 'Jasa hias taman profesional dengan pengalaman 40 tahun. Desain taman minimalis, taman Jepang, taman tropis, taman herbal, vertical garden, taman rooftop. Garansi tanaman 1 bulan. Maintenance bulanan tersedia.',
    price: 500000,
    priceMax: 10000000,
    benefit1: 'Pengalaman 40 Tahun',
    benefit2: 'Desain Custom Sesuai Kebutuhan',
    benefit3: 'Garansi Tanaman 1 Bulan',
    benefit4: 'Bahan Premium Tanaman Pilihan',
    benefit5: 'Maintenance Bulanan Tersedia',
    waText: 'Halo Mas Iis, saya mau jasa hias taman',
    imageUrl: '/services/taman.svg',
    bonus: 'Gratis konsultasi desain',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 16,
  },
  {
    name: 'Jasa Hiburan Angklung',
    slug: 'jasa-hiburan-angklung',
    category: 'Event',
    shortDesc: '10 personil angklung dengan kostum tradisional',
    detailDesc: 'Jasa hiburan angklung 10 personil dengan kostum tradisional Sunda. Free interaktif 15 menit dimana penonton bisa ikut bermain. Lagu Sunda dan Nasional. Bisa request lagu. Cocok untuk acara adat, pernikahan, khitanan, seminar, dan perkumpulan.',
    price: 1200000,
    priceMax: 3000000,
    benefit1: '10 Personil Angklung Berpengalaman',
    benefit2: 'Kostum Tradisional Sunda',
    benefit3: 'Free Interaktif 15 Menit',
    benefit4: 'Lagu Sunda dan Nasional',
    benefit5: 'Bisa Request Lagu',
    waText: 'Halo Mas Iis, saya mau jasa angklung',
    imageUrl: '/services/angklung.svg',
    bonus: 'Free interaktif 15 menit',
    slotStatus: 'Slot Tersedia',
    slotAvailable: true,
    order: 17,
  },
]

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const force = searchParams.get('force') === 'true'

    // Check if already seeded
    const existingCount = await db.service.count()

    if (existingCount > 0 && !force) {
      return NextResponse.json({
        success: true,
        message: `Database already has ${existingCount} services. Use ?force=true to re-seed.`,
      })
    }

    // If force, delete existing data
    if (force && existingCount > 0) {
      await db.fAQ.deleteMany()
      await db.booking.deleteMany()
      await db.serviceImage.deleteMany()
      await db.testimonial.deleteMany()
      await db.landingPage.deleteMany()
      await db.article.deleteMany()
      await db.siteConfig.deleteMany()
      await db.service.deleteMany()
    }

    // Seed services
    for (const svc of SERVICES) {
      const service = await db.service.create({ data: svc })
      // Auto-create landing page for each service
      await db.landingPage.create({
        data: {
          serviceId: service.id,
          headline: svc.name,
          subheadline: svc.shortDesc,
          ctaText: 'Hubungi Sekarang',
          sections: JSON.stringify([
            { type: 'hero', title: svc.name, subtitle: svc.shortDesc },
            { type: 'benefits', title: 'Keunggulan Layanan', items: [svc.benefit1, svc.benefit2, svc.benefit3, svc.benefit4, svc.benefit5] },
            { type: 'pricing', title: 'Harga', price: svc.price, priceMax: svc.priceMax },
            { type: 'cta', title: 'Pesan Sekarang', bonus: svc.bonus },
          ]),
        },
      })
    }

    // Seed sample articles
    await db.article.createMany({
      data: [
        {
          title: 'Tips Merawat Laptop Agar Awet',
          slug: 'tips-merawat-laptop',
          excerpt: 'Pelajari cara merawat laptop agar tetap performa optimal selama bertahun-tahun.',
          content: '<h2>1. Bersihkan Secara Rutin</h2><p>Bersihkan keyboard dan layar minimal 1 minggu sekali...</p><h2>2. Jangan Makan di Dekat Laptop</h2><p>Remah makanan bisa masuk ke keyboard...</p><h2>3. Gunakan Cooling Pad</h2><p>Overheating adalah musuh utama laptop...</p>',
          published: true,
        },
        {
          title: 'Cara Menyelesaikan Skripsi 1 Bulan',
          slug: 'skripsi-1-bulan',
          excerpt: 'Strategi praktis menyelesaikan skripsi dalam waktu singkat tanpa stres.',
          content: '<h2>1. Tentukan Judul Secepat Mungkin</h2><p>Jangan terlalu lama mencari judul sempurna...</p><h2>2. Buat Timeline Ketat</h2><p>Bagi waktu per bab...</p>',
          published: true,
        },
        {
          title: 'Mengapa Website Penting untuk Bisnis',
          slug: 'website-untuk-bisnis',
          excerpt: 'Alasan mengapa setiap bisnis membutuhkan website di era digital.',
          content: '<h2>1. Kredibilitas Bisnis</h2><p>75% konsumen menilai kredibilitas dari website...</p>',
          published: true,
        },
      ],
    })

    // Seed site config
    await db.siteConfig.createMany({
      data: [
        { key: 'hero_image', value: '/hero-bg-new.png' },
        { key: 'site_name', value: 'Mas Iis - Warung Solusi' },
        { key: 'site_description', value: 'Warung Solusi Terpercaya di Cirebon. 17 jasa lengkap.' },
        { key: 'whatsapp_number', value: '0882-0008-58698' },
        { key: 'address', value: 'Sindanglaut, Kab. Cirebon, Jawa Barat' },
        { key: 'operating_hours', value: 'Senin-Sabtu 08.00-21.00 WIB' },
        { key: 'bank_info', value: 'BCA Transfer' },
        { key: 'warranty_policy', value: 'Garansi hingga 30 hari untuk sebagian besar jasa' },
        { key: 'stats_customers', value: '500+' },
        { key: 'stats_rating', value: '4.9/5' },
        { key: 'stats_services', value: '17' },
      ],
    })

    const count = await db.service.count()
    return NextResponse.json({
      success: true,
      message: `Seeded ${count} services with landing pages, articles, and site config!`,
    })
  } catch (error) {
    console.error('Setup error:', error)
    return NextResponse.json(
      { success: false, error: String(error) },
      { status: 500 }
    )
  }
}
